#pragma once
// -----------------------------------------------------------------------------
// AppPaths.h
//
// Single source of truth for the LittleFS paths this firmware owns and
// writes to at runtime (config, device state, history). Referenced by both
// the owning manager (ConfigManager/DeviceManager/EnvironmentManager) and
// StorageManager::wipeAll(), so a factory reset can delete exactly these
// paths — and nothing else, importantly NOT the static dashboard assets
// under /, /css/, /js/ that were uploaded via `pio run -t uploadfs` and
// aren't regenerated by the firmware itself.
// -----------------------------------------------------------------------------

namespace paths {

constexpr const char *CONFIG = "/config.json";
constexpr const char *DEVICE_STATE = "/device.json";
constexpr const char *ENV_HISTORY = "/history/env.bin";

} // namespace paths
